title: "데이터 분석가 조민서"
description: "안녕하세요 데이터 분석가 조민서입니다."
baseurl: ""
url: "https://icedo724.github.io"

theme: cvless

# site settings
taglong: "데이터 분석가 조민서의 포트폴리오입니다."
tagshort: "데이터 분석 포트폴리오"

# author settings
author:
  name: "조민서"
  email: "본인이메일@gmail.com"
# photo: assets/files/photo.jpg
joblines:
  - Data Analyst
# address: Foobar Hall 1.23
# phone: +1 234 567 890

# profile links
profile:
  github: https://github.com/icedo724
  cv: true

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never