title: "데이터 분석가 조민서"
description: "안녕하세요 조민서입니다."
baseurl: ""
url: "https://icedo724.github.io"

theme: cvless

# site settings
taglong: "누구보다 깊게 소비했기에, 누구보다 정확하게 분석합니다."
tagshort: "데이터 분석 포트폴리오"

# author settings
author:
  name: "조민서"
  email: "icedo724@gmail.com"
  photo: "https://i.imgur.com/yKPdr7y.jpeg"
joblines:
  - Data Analyst
address: "경기도 의왕시"
phone: "PHONE_PLACEHOLDER"

# profile links
profile:
  github: https://github.com/icedo724
  cv: true
  projects: true

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never